# Generated by Django 3.1.1 on 2020-09-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
